version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: install aws
         command: |
          echo "hello World"
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
         name: List the content
         command: |
           ls -la
           pwd
           docker --version
           echo $CIRCLE_PR_NUMBER
      - run: 
         name: Log in to AWS ECR
         command: eval $(aws ecr get-login --no-include-email --region eu-west-1)
      - run: 
         name: Publish to ECR
         command: |
            docker build -t 873930443481.dkr.ecr.eu-west-1.amazonaws.com/test-circleci:latest -t 873930443481.dkr.ecr.eu-west-1.amazonaws.com/test-circleci:$CIRCLE_SHA1 .
            docker push 873930443481.dkr.ecr.eu-west-1.amazonaws.com/test-circleci:latest
            docker push 873930443481.dkr.ecr.eu-west-1.amazonaws.com/test-circleci:$CIRCLE_SHA1
      - run:
         name: Install Kubectl & Iam Authneticator
         command: |
           ./kubectl_install.sh
      - run:
         name: Deploy to Cluster
         command: |
           # Applying the New Image to Kubernetes
            if kubectl describe deployment/nginx-deployment; then
              echo "if Condition not exist"
              kubectl set image deployment nginx-deployment nginx=nginx:$CIRCLE_SHA1 --record
            else
              echo "Does not Exit"
              kubectl create -f nginx.yaml --record
            fi


