version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
         name: List the content
         command: |
           ls -la
           pwd
           echo $CIRCLE_SHA1
           echo $CIRCLE_TAG
           echo $CIRCLE_BRANCH
     
