version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    envr
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: install aws
         command: |
          echo "hello World"
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
         name: List the content
         command: |
           ls -la
           pwd
           docker --version
           echo $CIRCLE_PR_NUMBER
      - run: 
         name: Log in to AWS ECR
         command: eval $(aws ecr get-login --no-include-email --region eu-west-1)
      - run:
         name: Install Kubectl 
         command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.5/2018-12-06/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
            kubectl version --short --client 
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_REGION
            aws eks list-clusters
            aws eks update-kubeconfig --name eks-sbx-cluster
            kubectl get svc

      # - run: 
      #    name: "Bulid & Push Docker Image"
      #    command: |
      #      docker build -t 873930443481.dkr.ecr.eu-west-1.amazonaws.com/test-circleci:$CIRCLE_SHA1 .
      #      docker push 873930443481.dkr.ecr.eu-west-1.amazonaws.com/test-circleci:$CIRCLE_SHA1
