version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Install aws CLI
         command: |
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: 
         name: Log in to AWS ECR
         command: eval $(aws ecr get-login --no-include-email --region eu-west-1)
      - run:
         name: Publish to ECR, Deploy to Cluster
         command: |
           ./deploy.sh


